//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detailss
    {
        public int DetailId { get; set; }
        public Nullable<int> DetailTypeId { get; set; }
        public Nullable<int> DetailNameId { get; set; }
        public Nullable<int> MarkaId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> Kol { get; set; }
    
        public virtual DetailNames DetailNames { get; set; }
        public virtual DetailType DetailType { get; set; }
        public virtual Marka Marka { get; set; }
        public virtual Model Model { get; set; }
    }
}
