//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nkorzina
    {
        public int Id { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> MarkaId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> Kol { get; set; }
    }
}
